### ISSUE TITLE
Panic on storageos/node:1.0.0-rc4

### ISSUE THREAD

**Issue by blaggacao** [storageos/deploy#8] opened 2018-09-25 21:42 UTC
- On `storageos/node:1.0.0-rc4`
- Deployed as described [here](https://docs.storageos.com/docs/platforms/kubernetes/install/1.10) (CSI)
- On a rancher provisioned kubernetes cluster

I get the following panic:

```
time="2018-09-25T21:17:04Z" level=info msg="by using this product, you are agreeing to the terms of the StorageOS Ltd. End User Subscription Agreement (EUSA) found at: https://eusa.storageos.com" module=command
time="2018-09-25T21:17:04Z" level=info msg=starting address=140.82.30.224 hostname=vultr id=fc5001e8-6b22-0610-12d9-35df3fdc88b8 join=XXX.XXX.XXX.XXX module=command version="StorageOS 1.0.0 (0bbd203), built: 2018-07-18T163409Z"
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
code.storageos.net/storageos/control/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).Region(0xc42000e170, 0xc4201fd000, 0x16, 0xc42047af40, 0xc42092d800)
/go/src/code.storageos.net/storageos/control/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:122 +0xa3
code.storageos.net/storageos/control/integration/iaas/ec2.(*Provider).GetZone(0xc42000d140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4205da778, 0xc4205da820)
/go/src/code.storageos.net/storageos/control/integration/iaas/ec2/provider.go:112 +0x59
code.storageos.net/storageos/control/controlplane.applyProviderMetadata(0xc420a00000, 0x462b700, 0xc42000d140, 0x0, 0xc4200107b0)
/go/src/code.storageos.net/storageos/control/controlplane/node.go:213 +0x1de
code.storageos.net/storageos/control/controlplane.applyMetadata(0xc420a00000, 0x9, 0x45fffd0)
/go/src/code.storageos.net/storageos/control/controlplane/node.go:208 +0x66
code.storageos.net/storageos/control/controlplane.writeNodeBootstrapConfig(0xc4201e0b60, 0xc4202b4900, 0x4616740, 0xc420506a20)
/go/src/code.storageos.net/storageos/control/controlplane/node.go:173 +0xbec
code.storageos.net/storageos/control/controlplane.Create(0xc4202b4900, 0x4602e20, 0xc4202904c8, 0x463fd40, 0xc42034c200, 0xc42034c300, 0x45f5908, 0x7)
/go/src/code.storageos.net/storageos/control/controlplane/server.go:209 +0xc3d
code.storageos.net/storageos/control/command/server.(*Command).Run(0xc4201e0a10, 0xc4200c4010, 0x0, 0x0, 0x0)
/go/src/code.storageos.net/storageos/control/command/server/command.go:125 +0x998
code.storageos.net/storageos/control/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc420080b40, 0xc420080b40, 0xc420226aa0, 0x0)
/go/src/code.storageos.net/storageos/control/vendor/github.com/mitchellh/cli/cli.go:255 +0x1eb
main.realMain(0xc4200a0058)
/go/src/code.storageos.net/storageos/control/main.go:38 +0x126
main.main()
/go/src/code.storageos.net/storageos/control/main.go:26 +0x22
```

Ticket: 373

**Comment by croomes** [comment] 2019-04-01 11:41
Sorry we missed responding to this report.  The root cause was fixed in https://github.com/aws/aws-sdk-go/pull/2380 and included in StorageOS 1.1.0.

**Closed as completed by croomes** 2019-04-01 11:41 UTC
